# Generated by Django 5.0.6 on 2024-07-05 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='amout',
            new_name='amount',
        ),
    ]
